ClusterAutoscaler: first fit decreasing binpacking-based estimate algorithm
kubernetes/contrib pull request #1741
Opened 2016-09-13 21:02 UTC by mwielgus

This should help with #1722.

The goal of the PR is to provide a better, immediate estimation of how many nodes should be added to a cluster to handle a given set of pods. The idea is to run an approximate bin-packing of pending pods to the cluster using FFD heuristic. See 

https://en.wikipedia.org/wiki/Bin_packing_problem
 
for details.

cc: @piosz @fgrzadkowski

2016-09-16 09:07 UTC, fgrzadkowski commented on cluster-autoscaler/estimator/binpacking_estimator.go
> +func (estimator *BinpackingNodeEstimator) Estimate(pods []*kube_api.Pod, nodeTemplate *schedulercache.NodeInfo) int {
What does this function return?

2016-09-16 09:09 UTC, fgrzadkowski commented on cluster-autoscaler/estimator/binpacking_estimator.go
> +	// Score is defined as cpu_sum/node_capacity + mem_sum/node_capacity. With this pods that
Nitpick:
How about rephrasing second sentence to
"Pods that have bigger requirements should be processed first, thus have higher scores."

2016-09-16 09:10 UTC, fgrzadkowski commented on cluster-autoscaler/estimator/binpacking_estimator.go
> +	for _, pod := range pods {
Suggestion - I'd move score computation to a separate function to keep this function shorter and more readable.

2016-09-16 09:11 UTC, fgrzadkowski commented on cluster-autoscaler/estimator/binpacking_estimator.go
> +		if cpuCapcaity, ok := nodeTemplate.Node().Status.Capacity[kube_api.ResourceCPU]; ok && cpuCapcaity.MilliValue() > 0 {
s/cpuCapcaity/cpuCapacity

2016-09-16 09:11 UTC, fgrzadkowski commented on cluster-autoscaler/estimator/binpacking_estimator.go
> +		if memCapcaity, ok := nodeTemplate.Node().Status.Capacity[kube_api.ResourceMemory]; ok && memCapcaity.Value() > 0 {
s/memCapcaity/memCapacity

2016-09-16 09:16 UTC, fgrzadkowski commented on cluster-autoscaler/estimator/binpacking_estimator.go
> +	nodeWithPod := func(nodeInfo *schedulercache.NodeInfo, pod *kube_api.Pod) *schedulercache.NodeInfo {
Please add a comment:

"nodeWithPod function returns NodeInfo, which is a copy of nodeInfo argument with an additional pod scheduled on it"

2016-09-16 09:19 UTC, fgrzadkowski commented on cluster-autoscaler/estimator/binpacking_estimator_test.go
> +				kube_api.ResourceCPU:    *resource.NewMilliQuantity(1000, resource.DecimalSI),
Can we use `3*cpuPerPod` (or something) so that it's clear what's the relation with pod size?

2016-09-16 09:19 UTC, fgrzadkowski requested changes
Have you checked how this will work in large clusters? How much CPU would it use? How fast does this algorithm work with 1k nodes and many unschedulable pods?

2016-09-21 22:58 UTC, test-foxish commented
recomputing cla status...

2016-09-28 17:16 UTC, mwielgus commented on cluster-autoscaler/estimator/binpacking_estimator.go
> +func (estimator *BinpackingNodeEstimator) Estimate(pods []*kube_api.Pod, nodeTemplate *schedulercache.NodeInfo) int {
Done.

2016-09-28 17:20 UTC, mwielgus commented on cluster-autoscaler/estimator/binpacking_estimator.go
> +	for _, pod := range pods {
Done.

2016-09-28 17:21 UTC, mwielgus commented on cluster-autoscaler/estimator/binpacking_estimator.go
> +		if memCapcaity, ok := nodeTemplate.Node().Status.Capacity[kube_api.ResourceMemory]; ok && memCapcaity.Value() > 0 {
done

2016-09-28 17:22 UTC, mwielgus commented on cluster-autoscaler/estimator/binpacking_estimator.go
> +	nodeWithPod := func(nodeInfo *schedulercache.NodeInfo, pod *kube_api.Pod) *schedulercache.NodeInfo {
done.

2016-09-28 17:34 UTC, mwielgus commented
This code is not even yet enabled. Will be in the next PR (via a flag).

2016-09-28 17:34 UTC, mwielgus commented
All comments addressed. @fgrzadkowski PTAL.

2016-09-29 15:25 UTC, fgrzadkowski commented on cluster-autoscaler/estimator/binpacking_estimator.go
> +		if cpuCapacity, ok := nodeTemplate.Node().Status.Capacity[kube_api.ResourceCPU]; ok && cpuCapacity.MilliValue() > 0 {
Should this use `Allocatable` instead of `Capacity`? You're using `Allocatable` above.

The same below.

2016-09-29 15:27 UTC, fgrzadkowski commented on cluster-autoscaler/estimator/binpacking_estimator_test.go
> +				kube_api.ResourceCPU:    *resource.NewMilliQuantity(cpuPerPod*3-50, resource.DecimalSI),
I thought the idea is that you can fit 3 pods CPU-wise and 2 pods memory-wise. Now you can fit only 2 pods in both dimensions. Is this what you want to test?

2016-09-30 09:59 UTC, mwielgus commented on cluster-autoscaler/estimator/binpacking_estimator.go
> +		if cpuCapcaity, ok := nodeTemplate.Node().Status.Capacity[kube_api.ResourceCPU]; ok && cpuCapcaity.MilliValue() > 0 {
done.

2016-09-30 10:19 UTC, mwielgus commented on cluster-autoscaler/estimator/binpacking_estimator.go
> +		if cpuCapacity, ok := nodeTemplate.Node().Status.Capacity[kube_api.ResourceCPU]; ok && cpuCapacity.MilliValue() > 0 {
Right now it is the same, but yeah, we can use Allocatable.
Done.

2016-09-30 10:20 UTC, mwielgus commented on cluster-autoscaler/estimator/binpacking_estimator_test.go
> +				kube_api.ResourceCPU:    *resource.NewMilliQuantity(cpuPerPod*3-50, resource.DecimalSI),
No the idea was to fit only 2 pods per node (it doesn't matter whether cpu or memory limited).

2016-10-03 07:19 UTC, fgrzadkowski commented
LGTM

2016-10-04 08:43 UTC, fgrzadkowski approved these changes

2016-10-04 09:59 UTC, merged