Set verbosity levels for addon-resizer
kubernetes/contrib pull request #2345
Opened 2017-01-25 16:34 UTC by Crassirostris

Fix https://github.com/kubernetes/contrib/issues/2337

Set verbosity levels according to https://github.com/kubernetes/community/blob/master/contributors/devel/logging.md.

CC @Q-Lee @piosz

2017-01-26 12:23 UTC, piosz requested changes

2017-01-26 12:23 UTC, piosz commented on addon-resizer/nanny/nanny_lib.go
> +		log.V(0).Infof("Resources are not within the expected limits, updating the deployment. Actual: %+v Expected: %+v", *resources, *expResources)
Just Infof, remove V(0).

2017-01-26 12:23 UTC, piosz commented on addon-resizer/nanny/nanny_lib.go
> +			log.V(4).Infof("Resources are within the expected limits. Actual: %+v Expected: %+v", *resources, *expResources)
Optional: As for now I can see resources in the following format
```
cpu:{i:{value:88 scale:-3} d:{Dec:<nil>} s:88m Format:DecimalSI}
```
How about making it more readable for a human reader?

2017-01-26 12:32 UTC, Crassirostris commented on addon-resizer/nanny/nanny_lib.go
> +		log.V(0).Infof("Resources are not within the expected limits, updating the deployment. Actual: %+v Expected: %+v", *resources, *expResources)
This a good question, whether to use V(0) explicitly or not. I looked up and it seems like just infof is a much more popular approach.

ACK, that should also be mentioned in guide

2017-01-26 12:33 UTC, Crassirostris commented on addon-resizer/nanny/nanny_lib.go
> +			log.V(4).Infof("Resources are within the expected limits. Actual: %+v Expected: %+v", *resources, *expResources)
I tried to touch as little code as possible. I think I will spend much more time making it better-looking

2017-01-26 12:41 UTC, Crassirostris commented on addon-resizer/nanny/main/pod_nanny.go
> +	log.V(1).Infof("Invoked by %v", os.Args)
This contradicts logging guide, where configuration details should be under V(1).

However, I tend to agree that O(1) logs should be on level 0. ACK

2017-01-26 12:47 UTC, Crassirostris commented
@piosz PTAL

2017-01-26 16:15 UTC, piosz approved these changes

2017-01-26 16:15 UTC, piosz commented on addon-resizer/nanny/nanny_lib.go
> +			log.V(4).Infof("Resources are within the expected limits. Actual: %+v Expected: %+v", *resources, *expResources)
Sure. Created #2351

2017-01-26 16:15 UTC, piosz commented
cc @Q-Lee

2017-01-26 16:16 UTC, piosz commented
/approve

2017-01-26 16:17 UTC, piosz commented
Also please bump the version in Kubernetes

2017-01-27 15:08 UTC, Crassirostris commented
@k8s-bot test this

2017-01-27 21:32 UTC, Crassirostris commented
/approve

2017-01-27 21:39 UTC, merged