fix etcd start twice
kubernetes/contrib pull request #2436
Opened 2017-03-02 05:24 UTC by xialonglee

There are two register variables use the same name `etcd_started`, the first one was defined in `etcd-start.yml` and the second one was in `etcd2-start.yml`.
The later var will override the previous var even though the task was skipped, see 

http://docs.ansible.com/ansible/playbooks_variables.html#registered-variables

> Note
If a task fails or is skipped, the variable still is registered with a failure or skipped status, the only way to avoid registering a variable is using tags.

In not-coreos case, this will cause etcd restart immediately during its first start process. 
It is not harmless, it will occationally cause etcd unhealthy and could not start normally again , see https://github.com/kubernetes-incubator/kargo/issues/342

2017-03-02 05:28 UTC, xialonglee commented
cc @ingvagabund

2017-03-03 07:38 UTC, galexrt requested changes
:+1: except the small "change" comment I added.

2017-03-03 07:38 UTC, galexrt commented on ansible/roles/etcd/tasks/main.yml
> +  when: etcd_modified is not defined or (etcd_modified is defined and etcd_started.changed == false and etcd_started2.changed == false)
Removing the redundant `(etcd_modified is defined and` in this PR would be good, so it's done.

2017-03-03 08:27 UTC, xialonglee commented
@galexrt fixed fixed : )

2017-03-03 08:28 UTC, galexrt approved these changes

2017-03-07 22:10 UTC, ingvagabund commented
I would rather use dynamic includes and get rid of the etcd[0-9]_modifed style of variables.

2017-03-10 04:57 UTC, xialonglee commented
fixed it, looks better : ) @ingvagabund

2017-03-13 14:08 UTC, ingvagabund commented
@redhat-k8s-bot test please

2017-03-13 14:08 UTC, ingvagabund commented
/approve

2017-03-13 14:09 UTC, ingvagabund approved these changes

2017-03-13 14:09 UTC, ingvagabund commented on ansible/roles/etcd/tasks/start.yml
> +- include: "{% if not is_coreos %}etcd-start{% else %}etcd2-start{% endif %}.yml"
Given all the roles need some additional refactoring, this is ok.

2017-03-14 11:16 UTC, ingvagabund commented
@redhat-k8s-bot test please

2017-03-14 11:41 UTC, xialonglee commented on ansible/roles/etcd/tasks/start.yml
> +- include: "{% if not is_coreos %}etcd-start{% else %}etcd2-start{% endif %}.yml"
You mean refactoring all roles that include tasks like this to dynamic include? or just in 'etcd' role?

2017-03-14 11:43 UTC, ingvagabund commented on ansible/roles/etcd/tasks/start.yml
> +- include: "{% if not is_coreos %}etcd-start{% else %}etcd2-start{% endif %}.yml"
Yeah, all roles. The dynamic include is a recent feature of the ansible. So is `block`. I see a lot of places where the roles can be improved.

2017-03-14 11:55 UTC, xialonglee commented on ansible/roles/etcd/tasks/start.yml
> +- include: "{% if not is_coreos %}etcd-start{% else %}etcd2-start{% endif %}.yml"
I think it should take a little time to do this and testing ...
Should i just refactoring these include statement of the 'etcd' role this pr?

2017-03-14 11:56 UTC, ingvagabund commented on ansible/roles/etcd/tasks/start.yml
> +- include: "{% if not is_coreos %}etcd-start{% else %}etcd2-start{% endif %}.yml"
It is ok. Let's keep the PR as it is.

2017-03-14 11:58 UTC, ingvagabund commented
@redhat-k8s-bot test please

2017-03-14 11:58 UTC, xialonglee commented on ansible/roles/etcd/tasks/start.yml
> +- include: "{% if not is_coreos %}etcd-start{% else %}etcd2-start{% endif %}.yml"
okay : )

2017-03-14 12:16 UTC, ingvagabund commented
/lgtm

2017-03-14 12:17 UTC, ingvagabund commented
/lgtm

2017-03-14 12:17 UTC, merged