ansible: add cluster_public_hostname
kubernetes/contrib pull request #2452
Opened 2017-03-06 17:35 UTC by talset

The cluster_hostname is already present (to be able to reach the
private/internal vip kube api).
The goal of cluster_public_hostname is to have the same thing but for
public access to the api.

If the public vip domain is not part of the certificat, when you will
try to access to the api via kubectl you will have something like that :

Unable to connect to the server: x509: certificate is valid for
cluster_hostname, master0, master1 ..., not cluster_public_hostname

2017-03-06 18:23 UTC, galexrt requested changes
Just the two spaces to remove. The other changes LGTM :+1:

2017-03-06 18:23 UTC, galexrt commented on ansible/roles/kubernetes/tasks/gen_certs.yml
> +    CLUSTER_PUBLIC_HOSTNAME: "{{ master_cluster_public_hostname |default('') }}"
Could you remove the spaces between `|default` and the variable.
(On line 39 and 40)

2017-03-07 08:22 UTC, talset commented
I signed it!

2017-03-07 08:25 UTC, talset commented
I signed it!

2017-03-07 08:29 UTC, talset commented
I signed it!

2017-03-07 08:44 UTC, ingvagabund commented
@redhat-k8s-bot test please

2017-03-08 13:02 UTC, talset commented
Suggested changes have been applied

2017-03-08 13:07 UTC, ingvagabund commented
@redhat-k8s-bot test please

2017-03-08 13:29 UTC, ingvagabund commented
/lgtm
/approve

2017-03-08 13:30 UTC, merged