Convert registry to k8s.gcr.io
kubernetes/contrib pull request #2814
Opened 2017-12-22 18:00 UTC by thockin

This PR was auto-generated.  Please apply human expertise to review for correctness.

Followup to https://github.com/kubernetes/kubernetes/pull/54174

xref https://github.com/kubernetes/release/issues/281

2017-12-22 18:19 UTC, bowei commented
lgtm

2017-12-27 06:56 UTC, MrHohn approved these changes
/lgtm

2017-12-28 10:28 UTC, porridge requested changes
Sorry, but this does not work.
I can push to the old location but not the new one:

```
porridge@kielonek:~/projects/go/src/k8s.io/contrib/perfdash$ gcloud docker -- tag gcr.io/google_containers/perfdash:0.8 k8s.gcr.io/perfdash:0.8
porridge@kielonek:~/projects/go/src/k8s.io/contrib/perfdash$ gcloud docker -- push  k8s.gcr.io/perfdash:0.8
The push refers to a repository [k8s.gcr.io/perfdash]
45f4f6715eed: Pushing [==================================================>] 137.2 kB
eacb8c6cad16: Pushing [==========================>                        ] 2.819 MB/5.321 MB
df6868d54704: Pushing [=====================>                             ] 2.805 MB/6.572 MB
8880784f79cf: Pushing [====>                                              ] 3.518 MB/36.78 MB
46ecc6c4543a: Pushing [>                                                  ] 2.126 MB/163.5 MB
5f70bf18a086: Waiting 
unexpected EOF
# (The above retries several times before failing)
porridge@kielonek:~/projects/go/src/k8s.io/contrib/perfdash$ gcloud docker -- tag gcr.io/google_containers/perfdash:0.8 gcr.io/google_containers/perfdash:0.8-test
porridge@kielonek:~/projects/go/src/k8s.io/contrib/perfdash$ gcloud docker -- push  gcr.io/google_containers/perfdash:0.8-test
The push refers to a repository [gcr.io/google_containers/perfdash]
45f4f6715eed: Layer already exists 
eacb8c6cad16: Layer already exists 
df6868d54704: Layer already exists 
8880784f79cf: Layer already exists 
46ecc6c4543a: Layer already exists 
5f70bf18a086: Layer already exists 
0.8-test: digest: sha256:b1ed038f1e032ea33fb48672d779f96a4c225140381ec8ba7ee29648dae2981f size: 1783
```

2017-12-28 17:14 UTC, thockin commented
@dekkagaijin  I, too, am experiencing issues.  This all worked at some point.

```
thockin@freakshow2 kubernetes gcr-vanity /$ docker images | egrep '(pause|thtest)'

thockin@freakshow2 kubernetes gcr-vanity /$ docker pull gcr.io/google_containers/pause
Using default tag: latest
latest: Pulling from google_containers/pause
a3ed95caeb02: Pull complete 
4964c72cd024: Pull complete 
Digest: sha256:a78c2d6208eff9b672de43f880093100050983047b7b0afe0217d3656e1b0d5f
Status: Downloaded newer image for gcr.io/google_containers/pause:latest

thockin@freakshow2 kubernetes gcr-vanity /$ docker images | egrep '(pause|thtest)'
gcr.io/google_containers/pause                   latest                        350b164e7ae1        3 years ago         239.8 kB

thockin@freakshow2 kubernetes gcr-vanity /$ docker tag gcr.io/google_containers/pause k8s.gcr.io/thtest:thtest 

thockin@freakshow2 kubernetes gcr-vanity /$ docker images | egrep '(pause|thtest)'
gcr.io/google_containers/pause                   latest                        350b164e7ae1        3 years ago         239.8 kB
k8s.gcr.io/thtest                                thtest                        350b164e7ae1        3 years ago         239.8 kB

thockin@freakshow2 kubernetes gcr-vanity /$ gcloud docker -- push k8s.gcr.io/thtest:thtest
The push refers to a repository [k8s.gcr.io/thtest]
5f70bf18a086: Layer already exists 
e16a89738269: Pushing [==================================================>] 241.7 kB
unexpected EOF
```

2017-12-28 19:18 UTC, dekkagaijin commented
2 possible solutions: updated gcloud to >= 183.0.0 (where k8s.gcr.io was added as a default domain) or use `gcloud docker -s k8s.gcr.io -- push ...`

2017-12-28 19:20 UTC, thockin commented
Confirmed, update worked for me

On Thu, Dec 28, 2017 at 11:18 AM, Jake Sanders <notifications@github.com>
wrote:

> 2 possible solutions: updated gcloud to >= 183.0.0 (where k8s.gcr.io was
> added as a default domain) or use gcloud docker -s k8s.gcr.io -- push ...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/contrib/pull/2814#issuecomment-354342375>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFVgVHCaf2uNGvliyE1B62fMImRIUGMUks5tE-migaJpZM4RLSS9>
> .
>

2017-12-29 07:46 UTC, porridge approved these changes
The `-s` flag worked as well.
/lgtm

2018-01-02 19:42 UTC, mikedanese commented
/approve

2018-01-13 20:32 UTC, mikedanese commented
/approve

2018-01-17 20:18 UTC, dekkagaijin requested changes

2018-01-17 20:18 UTC, dekkagaijin commented on for-demos/proxy-to-service/Makefile
> +PREFIX = k8s.gcr.io
`REGISTRY = staging-k8s.gcr.io`

...

```
container:
	docker build --pull -t $(REGISTRY)/$(NAME):$(TAG) .

push:
	gcloud docker -s REGISTRY-- push $(REGISTRY)/$(NAME):$(TAG)
```

2018-01-17 20:18 UTC, dekkagaijin commented on images/haproxy/Makefile
> +PREFIX = k8s.gcr.io/haproxy
```
REGISTRY = staging-k8s.gcr.io
PREFIX = $(REGISTRY)/haproxy
```

...

```
push: container
	gcloud docker -s $(REGISTRY) -- push $(PREFIX):$(TAG)
```

2018-01-17 20:18 UTC, dekkagaijin commented on ingress/echoheaders-redirect/Makefile
> +PREFIX = k8s.gcr.io/echoserver-redirect
```
REGISTRY = staging-k8s.gcr.io
PREFIX = $(REGISTRY)/echoserver-redirect

container:
	docker build --pull -t $(PREFIX):$(TAG) .

push: container
	gcloud docker -s $(REGISTRY) -- push $(PREFIX):$(TAG)
```

2018-01-17 20:18 UTC, dekkagaijin commented on keepalived-vip/Makefile
> +PREFIX = k8s.gcr.io/kube-keepalived-vip
```
REGISTRY = staging-k8s.gcr.io
PREFIX = $(REGISTRY)/kube-keepalived-vip
```
...
```
push: container
	gcloud docker -s $(REGISTRY) -- push $(PREFIX):$(TAG)
```

2018-01-17 20:18 UTC, dekkagaijin commented on node-perf-dash/Makefile
> +REPO = k8s.gcr.io
```
REGISTRY = staging-k8s.gcr.io
REPO = $(REGISTRY)

...

push: container
	gcloud docker -s $(REGISTRY) -- push $(REPO)/node-perf-dash:$(TAG)

2018-01-17 20:18 UTC, dekkagaijin commented on peer-finder/Makefile
> +PREFIX = k8s.gcr.io/peer-finder
```
REGISTRY = staging-k8s.gcr.io
PREFIX = $(REGISTRY)/peer-finder

...

push: container
	gcloud docker -s $(REGISTRY) -- push $(PREFIX):$(TAG)

2018-01-17 20:18 UTC, dekkagaijin commented on perfdash/Makefile
> +REPO = k8s.gcr.io
REGISTRY = staging-k8s.gcr.io
REPO = $(REGISTRY)

...

push: container
	gcloud docker -s $(REGISTRY) -- push $(REPO)/perfdash:$(TAG)

2018-01-17 20:18 UTC, dekkagaijin commented on scale-demo/vegeta/Makefile
> +	gcloud docker -- push k8s.gcr.io/loader:$(TAG)
`gcloud docker -s staging-k8s.gcr.io -- push staging-k8s.gcr.io/loader:$(TAG)`

2018-01-17 20:18 UTC, dekkagaijin commented on service-loadbalancer/Makefile
> +PREFIX ?= k8s.gcr.io/servicelb
```
REGISTRY ?= staging-k8s.gcr.io
PREFIX ?= $(REGISTRY)/servicelb

...

push: container
	$(GCLOUD) docker -s $(REGISTRY) -- push $(PREFIX):$(TAG)
```

2018-02-02 04:47 UTC, merged